apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adapter
  template:
    metadata:
      labels:
        app: adapter
    spec:
      imagePullSecrets:
        - name: my-docker-secret
      containers:
        - name: adapter
          image: hmack001/personal:adapter-v1.0
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
