apiVersion: v1
kind: Service
metadata:
  name: control-center
spec:
  selector:
    app: control-center
  ports:
    - protocol: TCP
      port: 9021
      targetPort: 9021
  type: LoadBalancer  # Or NodePort if you don't have a LoadBalancer
